### ISSUE TITLE
Wiki and other stuff

### ISSUE THREAD

**Issue by HoracioDos** [lxi-tools/lxi-tools#16]
Hello Martin
I don't want to bother you with small issues. I know you like snap but many people like me don't like snap or flatpak apps for many reasons. 
I didn't find any detailed instructions to compile lxi and lxi-tool like minimum packages needed or how to enable gui. (only a reference on eevblog) It would be nice if you can cut some parts from README.md and create a simple wiki with them. Also an official lxi-tool icon is needed ato create a desktop launcher.
I tried to set up a ppa last month and It's a lot of work so I left the idea behind. I've been playing with checkinstall to create .deb packages and it seems to work fine.
Thanks in advance!
![lxi-tools](https://user-images.githubusercontent.com/4549674/43599630-9954476e-965e-11e8-899d-6e5be40c0dd6.png)

**Comment by lundmar** [comment]
Hi HoracioDos,

The reason that I don't put any detailed description is that generally speaking the autotools configure and make lines will often be specific to the platform you are using. Hence the description is very generic and you will have to sort out the details relevant to your platform yourself. In a sense, the main documentation currently available for source compilation/installation is found via the "configure --help" option. 

Personally I don't want to start maintaining a wiki page for lxi-tools simply because it is would be more work for me. However, if you think such thing would be useful for you and others then I invite you to join the lxi-tools github organization and then I can enable the wiki and you can help maintain any information you think is relevant there.

Yes, I'm a fan of snaps because they are well structured and easy to deploy across a growing number of platforms. The big advantage of snap is that I can publish new versions literally within seconds of a new release. There is still room for proper package management for various distributions but for most end users that usually means running less up-to-date versions. Use of PPA's will eventually be replaced with the use of snaps - it's just the way things are heading. The only real downside of snaps is the increased download and installation data size. 

Regarding building details, icons etc. - you can find also some useful stuff here: https://github.com/lxi-tools/lxi-tools.snapcraft

**Comment by HoracioDos** [comment]
Thanks for your quick answer. I could write some instructions first and I will attach them here for your review and then you can enable the wiki. I would like to create some contents first. Please can you tag this issue as enhancement and on-hold?
I can see that lxi-gui snap version has an icon and launcher. I missed that.
Thanks again.

**Comment by lundmar** [comment]
I've sent your an invite. Once accepted you should be able to edit the wiki pages for the lxi-tools repository. The wiki is meant to be agile so feel free to play around with the layout and add whatever you feel is relevant.  No need for review before putting stuff in the wiki - we simply correct stuff directly in the wiki if necessary.

**Comment by lundmar** [comment]
Ok, I've set up the permissions so you should be able to edit the wiki now.

**Comment by HoracioDos** [comment]
Thanks I'll try to start writing this week.

**Comment by lundmar** [comment]
No hurry - you just fill in whatever you feel is missing in the README when you have time. :+1:

**Comment by lundmar** [comment]
So Horacio, are you giving up on the wiki idea? ;)

**Comment by HoracioDos** [comment]
Hello!
I'm sorry for the late reply. I've been very busy in the last two month and I had to put many things aside. I wasn't able to keep all the plates spinning in the air. I'll try to come back to electronics as soon I as can.

**Comment by lundmar** [comment]
Hi Horacio - no problem. I just wanted to know if you are still alive ;)
